project_id = "smisyziojkbiysudsrfj"

[functions.seed-all-templates]
verify_jwt = false

[functions.seed-detailed-templates]
verify_jwt = false

[functions.seed-interactive-elements]
verify_jwt = false

[functions.seed-premium-templates]
verify_jwt = false
