import { useState, useCallback, useEffect } from 'react';

export interface AppConfigEntry {
  values: Record<string, string>;
  connectedAt: string;
  isConnected: boolean;
}

const STORAGE_KEY = 'app_configs';

function loadAllConfigs(): Record<string, Record<string, AppConfigEntry>> {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

function saveAllConfigs(configs: Record<string, Record<string, AppConfigEntry>>) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(configs));
}

export const useAppConfig = (projectId: string | null) => {
  const [configs, setConfigs] = useState<Record<string, AppConfigEntry>>({});

  useEffect(() => {
    if (!projectId) return;
    const all = loadAllConfigs();
    setConfigs(all[projectId] || {});
  }, [projectId]);

  const saveConfig = useCallback((appKey: string, values: Record<string, string>) => {
    if (!projectId) return;
    const all = loadAllConfigs();
    if (!all[projectId]) all[projectId] = {};
    all[projectId][appKey] = {
      values,
      connectedAt: new Date().toISOString(),
      isConnected: true,
    };
    saveAllConfigs(all);
    setConfigs({ ...all[projectId] });
  }, [projectId]);

  const disconnectApp = useCallback((appKey: string) => {
    if (!projectId) return;
    const all = loadAllConfigs();
    if (all[projectId]?.[appKey]) {
      delete all[projectId][appKey];
      saveAllConfigs(all);
      setConfigs({ ...all[projectId] });
    }
  }, [projectId]);

  const getConfig = useCallback((appKey: string): AppConfigEntry | null => {
    return configs[appKey] || null;
  }, [configs]);

  const generateEnvContent = useCallback((appKey: string, fields: { key: string; label: string; secret?: boolean }[]): string => {
    const entry = configs[appKey];
    if (!entry) return '';
    const lines: string[] = ['# ─── App: ' + appKey.toUpperCase().replace(/-/g, '_') + ' ───'];
    fields.forEach(f => {
      const envKey = f.key.toUpperCase();
      const val = entry.values[f.key] || '';
      const prefix = f.secret ? '# SERVER-SIDE ONLY (never expose to client)\n' : '';
      lines.push(`${prefix}${envKey}=${val}`);
    });
    return lines.join('\n');
  }, [configs]);

  const generateFullEnv = useCallback((appCatalog: { key: string; configFields: { key: string; label: string; secret?: boolean }[] }[]): string => {
    const sections: string[] = [
      '# ════════════════════════════════════════════',
      '# Environment Variables — Generated by Website Builder',
      '# ════════════════════════════════════════════',
      '',
      '# ⚠️  NEVER commit this file to version control',
      '# ⚠️  Add .env to your .gitignore',
      '',
    ];
    const connectedApps = appCatalog.filter(a => configs[a.key]?.isConnected);
    if (connectedApps.length === 0) {
      sections.push('# No apps connected yet.');
    }
    connectedApps.forEach(app => {
      sections.push('');
      sections.push(generateEnvContent(app.key, app.configFields));
    });
    return sections.join('\n');
  }, [configs, generateEnvContent]);

  return { configs, saveConfig, disconnectApp, getConfig, generateEnvContent, generateFullEnv };
};
