// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smisyziojkbiysudsrfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtaXN5emlvamtiaXlzdWRzcmZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NDE1MTAsImV4cCI6MjA4ODUxNzUxMH0.thSn2Do3R0j7J-6y2P89l9UzK2zH1Zeg2Na1hWwBoKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});